### ISSUE TITLE
Blender forks - issue registering to the Blender icon

### ISSUE THREAD

**Issue by Draise14** [rovh/Noter#1]
# Issue
Issue:
![image](https://user-images.githubusercontent.com/35357409/90432959-b41e0480-e090-11ea-835a-4b3941981377.png)

Reason:
![image](https://user-images.githubusercontent.com/35357409/90432969-b7b18b80-e090-11ea-8e63-e6daf604ac53.png)

When registering the entries with the Noter addon in forks of Blender, some forks change or remove the Blender Icon menu and this is causing an issue on registry. 

# Request
Add the entries to the Window header (or other) menu instead:

Example:
![image](https://user-images.githubusercontent.com/35357409/90433094-e891c080-e090-11ea-8398-452e9d67f27e.png)

## Reason
The blender icon menu is not standard in most software, so finding the notes in there is also somewhat obscure. Having them show in window related menus or view related menus might make more sense and also make them more compatible with custom builds of the source code.

**Comment by rovh** [comment]
What do you think about the idea to add Noter's menu to the header panel?

**Comment by Draise14** [comment]
That could work. How many sub-entries does it have?

**Comment by rovh** [comment]
I changed the code. Now in case that error, Blender will move buttons to the Window header menu. I also added to the settings the ability to add a custom menu and the ability to customize whether the buttons should appear or not.

https://github.com/rovh/Noter/tree/1%2C0%2C2

Please write if the script works

**Comment by Draise14** [comment]
Script has the system commented out with some badly named classes, now I have fixed it. It was still pulling errors so dug in and had a look.
Here it is all packed up, but I will commit a branch also, and do a pull request. 
[Noter-1-0-3.zip](https://github.com/rovh/Noter/files/5115168/Noter-1-0-3.zip)

![Code_peKCAGdvju](https://user-images.githubusercontent.com/35357409/90991307-ac1d0380-e56d-11ea-88a5-cdcad5a77c0e.png)
